Enhancement/tour model
AttractorSchool/ESDP-AP-10-4 pull request #19
Opened 2023-05-18 13:57 UTC by Russo2642

2023-05-18 14:25 UTC, UralbekXD requested changes
Сделать ограничения на детальный просмотр тура
Тур с любым статусом кроме **CONFIRMED** доступен для просмотра автора.
CONFIRMED доступен для всех

2023-05-19 11:07 UTC, romeeeoo approved these changes, later dismissed
Тестовый мердж

2023-05-21 12:26 UTC, romeeeoo requested changes
1) решить конфликт в мирациях, 2 миграции под номером 004 (смерджи их)
2) закрыть создание тура для не аунтифицированныйх пользователей и для гидов только с одобренным профилем. 
3) поставить ограничение, чтобы нельзя было создать тур в прошлом
4) закрыть редактирование и удаление тура пока он на модерации

2023-05-22 14:22 UTC, romeeeoo approved these changes

2023-05-22 15:36 UTC, UralbekXD approved these changes
В будущем нужно дороботать проверку даты начало и конца тура

2023-05-22 15:36 UTC, merged