#60 Добавлена логика проверки по завершению тура. Настроены шаблоны п…
AttractorSchool/ESDP-AP-10-4 pull request #63
Opened 2023-06-07 06:50 UTC by Russo2642

…од вывод завершённых туров. В модели тура исправлены поля дата старта и дата окончания на datetimefield

2023-06-08 12:37 UTC, romeeeoo requested changes
1) когда идет его все еще можно бронить и отменять. Нужно после начала тура закрыть доступ для отмены и бронирования, Можно добавить еще статус STARTED
2) В ЛК у гида вывести завершенные туры. Сейчас они выводятся только владельцу профиля. А если турист заходит, то не выводятся
3) Добавить авторизацию на время создания тура, чтобы гид не мог создать тур который начнется менее чем через 3 дней
4) Убрать из списка туров туры которые начались

2023-06-09 11:20 UTC, Hamilekk commented on tours/views/crud_tours.py
> +        today = (datetime.now() + timedelta(hours=6)).strftime('%Y-%m-%d %H:%M')
Нужно сравнивать даты, а не строки

2023-06-09 11:21 UTC, UralbekXD approved these changes
Все работает, но нужно потом не конвертировать даты в строку, а так сравнивать

2023-06-09 11:28 UTC, romeeeoo reviewed
Все ок

2023-06-09 11:28 UTC, romeeeoo approved these changes
Все ок

2023-06-09 14:10 UTC, romeeeoo approved these changes
Все гуд

2023-06-09 14:10 UTC, romeeeoo commented on .python_history
А что это такое?)

2023-06-09 14:10 UTC, merged